### ISSUE TITLE
Standardise test structure and naming conventions

### ISSUE THREAD

**Issue by troyhunt** [HaveIBeenPwned/EmailAddressExtractor#28]
We've got a bit of a mismatch of conventions here between the original set of tests in `Program.cs`, the legacy tests I imported and new tests that have been written by later contributors. I don't really care which convention we go with, but I suggest standardising on file name (Program.cs seems a bit out of sync), test method name (we've got both Pascal case and underscores for word breaks), and test structure (there's a bunch of arrange / act / assert and more terse implementations).

I'm happy to leave the decision on how they're formatted to whoever wants to pick this up, main thing is to have conventions that others can come along and easily replicate.

**Comment by KonajuGames** [comment]
With #29 merged, this should also have been addressed.

**Comment by troyhunt** [comment]
Hmmm... not really, still very different conventions and structures. I'm not overly precious about it other than the fact that those who come after us are still faced with some doing arrange / act / assert and others not, some pluralising "test -> tests", the `MyAddressExtractorTest` class sitting in the `Program.cs` file etc.
