### ISSUE TITLE
Fix failing tests in LegacyTests

### ISSUE THREAD

**Issue by troyhunt** [HaveIBeenPwned/EmailAddressExtractor#5]
I've brought over a bunch of legacy tests from the original email extractor and dropped them into this solution. A bunch of them are failing due to weird edge cases I never properly handled in the regex. If someone would like to give these a go (any regex tragics out there?!), it'd be cool to get these handled properly.

**Comment by hiteshbedre** [comment]
@troyhunt Can you share some samples of edge cases you are thinking about? curious.
Here is my attempt on email address validation: https://regex101.com/r/34ha1f/1

**Comment by hiteshbedre** [comment]
Fixed all the mentioned cases in the pull request: https://github.com/HaveIBeenPwned/EmailAddressExtractor/pull/9

**Comment by troyhunt** [comment]
Still seeing a few failing testes (i.e. "dot_first_is_invalid")

**Comment by hiteshbedre** [comment]
@troyhunt Can we close this issue? or anything pending here?

**Comment by troyhunt** [comment]
I'm still seeing some failing tests, for example `domain_with_underscore_is_valid` and `unescaped_double_quote_is_invalid` (among others). Want to have a go at those?
